name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.HUBGIT_TOKEN }}

    - name: Build and Run Docker Image on Remote Server
      run: |
        sshpass -p "${{ secrets.REMOTE_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.REMOTE_IP }} << 'EOF'
          
          cd ~/peakrp-discord-bot
          git remote set-url origin git@github.com:TaylorsTheorem/peakrp-discord-bot.git
          git pull
          
          if docker exec peak-bot test -f /app/peak.db; then
            docker cp peak-bot:/app/peak.db /tmp/peak.db
          fi
          
          docker rm -f peak-bot
          
          docker image rm -f loading:peak-bot
          
          docker build --no-cache -t loading:peak-bot .
          
          docker run -d -e PEAK_BOT_TOKEN=${{ secrets.PEAK_BOT_TOKEN }} --name peak-bot loading:peak-bot
          
          if [ -f /tmp/peak.db ]; then
            docker cp /tmp/peak.db peak-bot:/app/peak.db
            rm /tmp/peak.db
          fi
        EOF
